import { Wallpaper } from '@/type/home';

export const wallpaperTypeList = [
  {
    id: 0,
    name: '热门',
  },
  {
    id: 1,
    name: 'ins风',
  },
  {
    id: 2,
    name: '纯色',
  },
  {
    id: 3,
    name: '明星',
  },
  {
    id: 4,
    name: '创意',
  },
  {
    id: 5,
    name: '简约',
  },
  {
    id: 6,
    name: '拟物',
  },
  {
    id: 7,
    name: '写真',
  },
];

export const wallpaperList: Wallpaper[] = [
  {
    id: 0,
    image: '/home/img1.webp',
    imageList: ['/home/img1.webp', '/home/img1.webp'],
    title: '雾霾蓝ins风极简',
    value: '这是一段描述文案，这是一段描这是一段描述文案，这是一段描',
    avatarImg: '/home/avatar.webp',
    avatarName: '伊恩特',
    usePeople: '4.8万人使用',
    status: 'hot',
    showPosition: 'left',
    useApp: [
      {
        name: '抖音',
        img: '/details/douYin.webp',
        accountNumber: '欣然',
      },
      {
        name: '微博',
        img: '/details/weiBo.webp',
        accountNumber: '欣然',
      },
    ],
  },
  {
    id: 1,
    image: '/home/img2.webp',
    imageList: [
      '/home/img2.webp',
      '/home/img2.webp',
      '/home/img2.webp',
      '/home/img2.webp',
    ],
    title: '雾霾蓝ins风极简',
    value: '这是一段描述文案，这是一段描这是一段描述文案，这是一段描',
    avatarImg: '/home/avatar.webp',
    avatarName: '亚比囧囧囧',
    usePeople: '2.3万人使用',
    status: 'new',
    showPosition: 'right',
    useApp: [
      {
        name: '微博',
        img: '/details/weiBo.webp',
        accountNumber: '橡皮刀',
      },
      {
        name: '小红书',
        img: '/details/redBook.webp',
        accountNumber: '橡皮刀',
      },
    ],
  },
  {
    id: 2,
    image: '/home/img2.webp',
    imageList: ['/home/img2.webp', '/home/img2.webp', '/home/img2.webp'],
    title: '雾霾蓝ins风极简',
    value: '这是一段描述文案，这是一段描这是一段描述文案，这是一段描',
    avatarImg: '/home/avatar.webp',
    avatarName: '呜哈哈',
    usePeople: '1.78万人使用',
    status: 'vip',
    showPosition: 'left',
    useApp: [
      {
        name: '微博',
        img: '/details/weiBo.webp',
        accountNumber: '孜然味',
      },
    ],
  },
  {
    id: 3,
    image: '/home/img3.webp',
    imageList: [
      '/home/img3.webp',
      '/home/img3.webp',
      '/home/img3.webp',
      '/home/img3.webp',
      '/home/img3.webp',
    ],
    title: '雾霾蓝ins风极简',
    value: '这是一段描述文案，这是一段描这是一段描述文案，这是一段描',
    avatarImg: '/home/avatar.webp',
    avatarName: '咦嘻嘻',
    usePeople: '9.3万人使用',
    status: 'normal',
    showPosition: 'right',
    useApp: [],
  },
  {
    id: 4,
    image: '/home/img2.webp',
    imageList: ['/home/img2.webp'],
    title: '雾霾蓝ins风极简',
    value: '这是一段描述文案，这是一段描这是一段描述文案，这是一段描',
    avatarImg: '/home/avatar.webp',
    avatarName: '嘎嘎嘎',
    usePeople: '3.5万人使用',
    status: 'normal',
    showPosition: 'left',
    useApp: [
      {
        name: '小红书',
        img: '/details/redBook.webp',
        accountNumber: '哇哈哈',
      },
      {
        name: 'WeiXin',
        img: '/details/weiXin.webp',
        accountNumber: '哇哈哈',
      },
    ],
  },
  {
    id: 5,
    image: '/home/img3.webp',
    imageList: [
      '/home/img3.webp',
      '/home/img3.webp',
      '/home/img3.webp',
      '/home/img3.webp',
    ],
    title: '雾霾蓝ins风极简',
    value: '这是一段描述文案，这是一段描这是一段描述文案，这是一段描',
    avatarImg: '/home/avatar.webp',
    avatarName: '嘟嘟嘟',
    usePeople: '11.5万人使用',
    status: 'normal',
    showPosition: 'right',
    useApp: [
      {
        name: '抖音',
        img: '/details/douYin.webp',
        accountNumber: '动动动',
      },
      {
        name: '微博',
        img: '/details/weiBo.webp',
        accountNumber: '动动动',
      },
      {
        name: '小红书',
        img: '/details/redBook.webp',
        accountNumber: '动动动',
      },
      {
        name: 'WeiXin',
        img: '/details/weiXin.webp',
        accountNumber: '动动动',
      },
    ],
  },
  {
    id: 6,
    image: '/home/img1.webp',
    imageList: ['/home/img1.webp', '/home/img1.webp', '/home/img1.webp'],
    title: '雾霾蓝ins风极简',
    value: '这是一段描述文案，这是一段描这是一段描述文案，这是一段描',
    avatarImg: '/home/avatar.webp',
    avatarName: '天亮了',
    usePeople: '9.01万人使用',
    status: 'normal',
    showPosition: 'left',
    useApp: [
      {
        name: '抖音',
        img: '/details/douYin.webp',
        accountNumber: '奥利给',
      },
      {
        name: '微博',
        img: '/details/weiBo.webp',
        accountNumber: '奥利给',
      },
      {
        name: 'WeiXin',
        img: '/details/weiXin.webp',
        accountNumber: '奥利给',
      },
    ],
  },
  {
    id: 7,
    image: '/home/img1.webp',
    imageList: [
      '/home/img1.webp',
      '/home/img1.webp',
      '/home/img1.webp',
      '/home/img1.webp',
      '/home/img1.webp',
      '/home/img1.webp',
      '/home/img1.webp',
      '/home/img1.webp',
    ],
    title: '雾霾蓝ins风极简',
    value: '这是一段描述文案，这是一段描这是一段描述文案，这是一段描',
    avatarImg: '/home/avatar.webp',
    avatarName: '地暗了',
    usePeople: '2.2万人使用',
    status: 'normal',
    showPosition: 'right',
    useApp: [
      {
        name: '微博',
        img: '/details/weiBo.webp',
        accountNumber: '天亮了',
      },
      {
        name: '小红书',
        img: '/details/redBook.webp',
        accountNumber: '天亮了',
      },
      {
        name: 'WeiXin',
        img: '/details/weiXin.webp',
        accountNumber: '天亮了',
      },
    ],
  },
  {
    id: 8,
    image: '/home/img2.webp',
    imageList: ['/home/img2.webp', '/home/img2.webp', '/home/img2.webp'],
    title: '雾霾蓝ins风极简',
    value: '这是一段描述文案，这是一段描这是一段描述文案，这是一段描',
    avatarImg: '/home/avatar.webp',
    avatarName: '脑白金',
    usePeople: '3.3万人使用',
    status: 'normal',
    showPosition: 'right',
    useApp: [
      {
        name: '抖音',
        img: '/details/douYin.webp',
        accountNumber: '超好喝',
      },
      {
        name: '微博',
        img: '/details/weiBo.webp',
        accountNumber: '超好喝',
      },
      {
        name: '小红书',
        img: '/details/redBook.webp',
        accountNumber: '超好喝',
      },
    ],
  },

  {
    id: 9,
    image: '/home/img3.webp',
    imageList: [
      '/home/img3.webp',
      '/home/img3.webp',
      '/home/img3.webp',
      '/home/img3.webp',
    ],
    title: '雾霾蓝ins风极简',
    value: '这是一段描述文案，这是一段描这是一段描述文案，这是一段描',
    avatarImg: '/home/avatar.webp',
    avatarName: '一杯cup',
    usePeople: '3.3万人使用',
    status: 'normal',
    showPosition: 'right',
    useApp: [
      {
        name: '抖音',
        img: '/details/douYin.webp',
        accountNumber: '很难喝',
      },
      {
        name: '微博',
        img: '/details/weiBo.webp',
        accountNumber: '很难喝',
      },
      {
        name: '小红书',
        img: '/details/redBook.webp',
        accountNumber: '很难喝',
      },
      {
        name: 'WeiXin',
        img: '/details/weiXin.webp',
        accountNumber: '很难喝',
      },
    ],
  },
];
